### ISSUE TITLE
Docs for libvala

### ISSUE THREAD

**Issue by craigbarnes** [vala-lang/valadoc-org#208]
As originally reported at flobrosch/valadoc-org#49.

**Comment by benwaffle** [comment]
btw libvala has a different package name for each version (e.g. libvala-0.42)

**Comment by benwaffle** [comment]
also you need to modify Makefile.am to get all the 5 vapis combined and with comments

**Comment by astavale** [comment]
Vala does have a`make` target for building the internal API docs:

```
cd docs
make internal-api-docs
xdg-open internal-apis/index.html
```
This can be used for development if you want. The API is changeable though. Ideally for an IDE there would be a mainline Vala language server, just like valadoc is now mainlined, that provides a stable JSON-RPC 2.0 API to be used by IDEs.

**Comment by benwaffle** [comment]
i believe that doesn't have any comments/descriptions

**Comment by astavale** [comment]
This is what I get:
![screenshot_2019-03-07 vala vala vala binding reference](https://user-images.githubusercontent.com/17455148/53997080-c7eed880-4132-11e9-97ff-821a7da2f4a5.png)
I don't think any comments/descriptions are missing? The API does seem some more documentation though...

**Comment by astavale** [comment]
By five VAPIs does that mean:

1. gee
2. vala
3. ccode
4. codegen
5. valadoc

?
If so then ccode, codegen and valadoc can be removed. ccode and codegen are further in to Vala's compilation process and won't be relevant to an IDE. Although valabind was an exception. Will an IDE need valadoc or is it better to use the existing valadoc CLI tool?

**Comment by ricotz** [comment]
The vala API documentation is available at https://gnome.pages.gitlab.gnome.org/vala/docs/index.html

**Comment by ricotz** [comment]
I consider this fixed with my last comment.
