### ISSUE TITLE
Is there a need for Font-awesome?

### ISSUE THREAD

**Issue by cjfloss** [vala-lang/valadoc-org#242]
Looking through the code I could only find two references to font-awesome icons and searching on github for [fa](https://github.com/Valadoc/valadoc-org/search?q=fa&unscoped_q=fa&type=Code) I get the same results.

On [index.php#L80](https://github.com/Valadoc/valadoc-org/blob/78b7d770ae06ae0eabf6af1e94a9b89bcf4aa52a/data/index.php#L80) for the reddit icon and [index.php#L81](https://github.com/Valadoc/valadoc-org/blob/78b7d770ae06ae0eabf6af1e94a9b89bcf4aa52a/data/index.php#L81) for the info icon.

So is there really a need for inporting all the font awesome for just two icons or am I missing something?

Removing it and running locally on firefox in the index page I get this:

**With font-awesome**
```
18 requests
394.60 KB / 361.66 KB transferred
Finish: 834 ms
DOMContentLoaded: 331 ms
load: 845 ms
```

**Without font-awesome**
```
16 requests
288.82 KB / 278.43 KB transferred
Finish: 429 ms
DOMContentLoaded: 296 ms
load: 451 ms
```

**Comment by danrabbit** [comment]
Yeah we don't need to load all of font awesome. It's overkill
