### ISSUE TITLE
Add VDA Documentation.

### ISSUE THREAD

**Issue by gavr123456789** [vala-lang/valadoc-org#244]
"Vala Data Access Library - Is a set of interfaces to access Data Bases written in Vala.  
It has a set of classes implementing this interfaces using GDA as backend."  
  
Build documents are already in `.gitlab-ci.yml`.  
[Repo](https://gitlab.gnome.org/esodan/libvda)  
GitLab Pages hosted [Docs](https://esodan.pages.gitlab.gnome.org/libvda/)

**Comment by benwaffle** [comment]
see https://github.com/Valadoc/valadoc-org#add-new-packages
