### ISSUE TITLE
WebKit docs out of date

### ISSUE THREAD

**Issue by cassidyjames** [vala-lang/valadoc-org#262]
i.e. This property has been supported in WebKit for a while, but it's not showing in the docs: https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html#webkit-settings-set-enable-back-forward-navigation-gestures

**Comment by cassidyjames** [comment]
It turns out this is a binding issue, as the property was added to WebKitGTK, but not the Vala bindings.

**Comment by ricotz** [comment]
The webkit2gtk bindings in vala 0.40.x are frozen to 2.20.x

**Comment by ricotz** [comment]
This should resolve itself with the switch to vala-team/daily ppa

**Comment by ricotz** [comment]
https://valadoc.org/webkit2gtk-4.0/WebKit.Settings.enable_back_forward_navigation_gestures.html
