### ISSUE TITLE
Add goocanvas

### ISSUE THREAD

**Issue by albfan** [vala-lang/valadoc-org#266]
**Describe the bug**
I'm developing an app based on GooCanvas and repeadtly find myself turning between:

- https://valadoc.org 
- https://developer.gnome.org/goocanvas/stable/ (translating concepts from C to vala)

As a library to easily paint, I think it is worth to have it on valadoc.org

**To Reproduce**
GooCanvas is a library developed with GObject so its valadoc can be generated automatically

**Expected behavior**

**Screenshots**
![Captura de pantalla de 2019-10-10 16-42-06](https://user-images.githubusercontent.com/220968/66579396-122eb100-eb7d-11e9-8ffb-eb1562cc003b.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser chrome

**Additional context**

Is there a general rule to publish a new library in valadoc.org, just to be sure. If I find other miss library I will try to provide directly the PR

**Comment by benwaffle** [comment]
I see the gir is present https://github.com/nemequ/vala-girs/blob/master/gir-1.0/GooCanvas-2.0.gir, but not the vapi. We need to run the build to see if it will work.

**Comment by ricotz** [comment]
@albfan @benwaffle Please use the one shipped with vala upstream! There is seems advisable to switch to a newer vala version to build valadoc.org. e.g. using what is in ppa:vala-team/next

**Comment by albfan** [comment]
@ricotz done! about adding new package, nvm https://github.com/vala-lang/valadoc-org#add-new-packages. Section to add new examples looks promising, I miss some basic examples here and there, so maybe goocanvas-2.0 is a good candidate for new vala examples. I will test things locally anyway.

@benwaffle thanks for taking care of this.

**Comment by albfan** [comment]
There're no Goo.Canvas results on valadoc.org. Is there any way to check what's happening?
