### ISSUE TITLE
g_str_match_string: second parameter incorrectly documented as "this" param

### ISSUE THREAD

**Issue by Prince781** [vala-lang/valadoc-org#273]
On [this page](https://valadoc.org/glib-2.0/string.match_string.html), `g_str_match_string ()` is incorrectly documented as `string.match_string (string search_term, bool accept_alternates) ` when it should be `string.match_string (string potential_hit, bool accept_alternates)`, since the C function is defined as
```C
gboolean
g_str_match_string (const gchar *search_term,
                    const gchar *potential_hit,
                    gboolean     accept_alternates);
```

**Comment by benwaffle** [comment]
https://gitlab.gnome.org/GNOME/vala/blob/master/vapi/glib-2.0.vapi#L1380-1381

```vala
	[CCode (instance_pos = "1.5", cname = "g_str_match_string")]
	public bool match_string (string search_term, bool accept_alternates);
```

how does instance_pos work?

**Comment by Prince781** [comment]
According to [this](https://wiki.gnome.org/Projects/Vala/Manual/Attributes), `instance_pos` is "The argument position of the instance that will be used as this in methods." It's strange that it's of type double rather than int.

**Comment by benwaffle** [comment]
Probably so that you can indicate that the instance variable goes between 2 others
