### ISSUE TITLE
Blank pages for SDL2

### ISSUE THREAD

**Issue by lxmcf** [vala-lang/valadoc-org#278]
**Describe the bug**
When trying to open the documentation for anything related to SDL2 (sdl2-net, sdl2-gfx, etc) will return a completely blank page and nothing will show up when searching from SDL2 components.

**To Reproduce**
1. Go to https://valadoc.org/sdl2/index.htm
2. See error

**Expected behavior**
Should normally just load up the documents

**Comment by aggsol** [comment]
I need this to work. I use valadoc.org daily.

**Comment by ricotz** [comment]
Duplicate of #281
