### ISSUE TITLE
Blank docs for package gobject-2.0

### ISSUE THREAD

**Issue by sixpounder** [vala-lang/valadoc-org#294]
Seems like docs for gobject-2.0 are gone?
![Screenshot from 2020-05-07 10-30-13](https://user-images.githubusercontent.com/187334/81272438-c75f1400-904d-11ea-83c8-766737c5e22c.png)

**Comment by tintou** [comment]
Should be fixed soon (upstream issue is https://gitlab.gnome.org/GNOME/vala/-/issues/989 )

**Comment by tintou** [comment]
Now back :slightly_smiling_face:
