### ISSUE TITLE
Disable Publish Action for forked repositories

### ISSUE THREAD

**Issue by astavale** [vala-lang/valadoc-org#295]
`.github/workflows/publish.yml` sets up a cron job to publish valadoc.org at 20:00 every day, this also runs for cloned versions of this repository. This jobs fails on the cloned version, e.g. see https://github.com/astavale/valadoc-org/actions

It would be nice not to use the resources for a job that is going to fail and also to stop the emails letting me know it has failed. There is no need for a cloned version to publish.

**Comment by lewisgoddard** [comment]
You can [Disable GitHub Actions for your fork](https://help.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository) in the meantime.
