### ISSUE TITLE
libvala documentation

### ISSUE THREAD

**Issue by ahrbe1** [vala-lang/valadoc-org#297]
I noticed the docs for libvala are missing. Any chance of an addition?

**Comment by astavale** [comment]
Duplicate of #208 

libvala isn't a public API, although tooling like language servers currently use it. I have now added how to build this documentation from source: https://wiki.gnome.org/Projects/Vala/DeveloperDocumentation#Documentation

A hosted copy is available from: https://gnome.pages.gitlab.gnome.org/vala/docs/vala/index.htm
