### ISSUE TITLE
Multiple SDL2 pages are down

### ISSUE THREAD

**Issue by lxmcf** [vala-lang/valadoc-org#310]
Multiple valadoc pages for SDL2 are currently down since the latest VAPI update, paghes that are down are as follows- 
- [sdl2](https://valadoc.org/sdl2/index.htm)
- [sdl-net](https://valadoc.org/sdl2-net/index.htm)
- [sdl2-mixer](https://valadoc.org/sdl2-mixer/index.htm)
- [sdl2-image](https://valadoc.org/sdl2-image/index.htm)
- [sdl2-gfx](https://valadoc.org/sdl2-gfx/index.htm)
- [sdl2-ttf](https://valadoc.org/sdl2-ttf/index.htm)

1. Go to the above pages
2. See blank page

**Comment by ricotz** [comment]
Fixed by https://github.com/vala-lang/valadoc-org/commit/c6bfd17e29ee8e35c0ee6a220761c32b00ed3f5c and https://gitlab.gnome.org/GNOME/vala-extra-vapis/-/commit/2cfd5a2f8e930f666909a8b6eac9923d06c7e965
