### ISSUE TITLE
Incorrect information on Aspect Frame

### ISSUE THREAD

**Issue by greenfierydragon** [vala-lang/valadoc-org#319]
On https://valadoc.org/gtk4/Gtk.AspectFrame.html It says that GtkAspectFrame derives from GtkFrame, which, since GTK4, it does not.

**Comment by ricotz** [comment]
Looks like an upstream issue https://github.com/GNOME/gtk/blob/master/gtk/gtkaspectframe.c#L30-L46

@ebassi Please take a look.

**Comment by ebassi** [comment]
Done: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3073
