### ISSUE TITLE
Struct fields being sorted lexically makes it hard to write struct literals

### ISSUE THREAD

**Issue by rrthomas** [vala-lang/valadoc-org#322]
**Describe the bug**
Struct fields (as well as methods) are lexically sorted in Valadoc pages. This means that one cannot tell the order of the fields to write a struct literal without field names.

A good example is: https://valadoc.org/glib-2.0/GLib.OptionEntry.html

Here, there are some struct literals in the example code. They do not match up with the field listing. At present, one needs to read the GLib VAPI to find the order, which is unfortunate.

Could the fields (and only the fields) be listed in declaration order?

**Comment by ricotz** [comment]
This is done by libvaladoc unconditionally at https://github.com/GNOME/vala/blob/master/libvaladoc/html/basicdoclet.vala#L986

**Comment by rrthomas** [comment]
Thanks, @ricotz, I had looked at the code and got as far as concluding that the sorting seemed not to be in the valadoc-org code! So this is really a Vala issue. I guess now the question is what is acceptable: for example, it would be straightforward to add a `sorted=true` optional parameter to `write_children`, and change the call at https://github.com/GNOME/vala/blob/master/libvaladoc/html/basicdoclet.vala#L774 to pass `false`.

**Comment by ricotz** [comment]
Yeah something like that, maybe a solution without breaking API for backporting.

**Comment by rrthomas** [comment]
What I suggested is backwards-compatible, no? (Add one optional argument which defaults to the current behaviour.)

**Comment by ricotz** [comment]
No, this would be an API/ABI break in C.

**Comment by rrthomas** [comment]
Ah, you only said "API" above :) So, I guess I could add another function `write_children_unsorted()`?

**Comment by ricotz** [comment]
Or make the sorting conditionally directly in `write_children` for struct fields only.

**Comment by rrthomas** [comment]
Making the sorting conditional on the caller would seem to introduce an unfortunate dependency of the callee on the caller. Factoring out `write_children_unsorted` seems cleaner.

I've tried this in https://gitlab.gnome.org/GNOME/vala/-/merge_requests/167/diffs

**Comment by ricotz** [comment]
This is handled by vala itself.
