### ISSUE TITLE
Is valadoc.org down?

### ISSUE THREAD

**Issue by Vysp3r** [vala-lang/valadoc-org#374]
I haven't been able to access the website for a week and kinda need it for my projects...

**Comment by BZHDeveloper** [comment]
Same thing here :(

**Comment by Vysp3r** [comment]
They told me on the Telegram server it's a problem with the ISP about IPv6 or something. It happened during an update or something like that. I may be wrong, but that's what I got for an answer.

**Comment by astavale** [comment]
I can't connect either. I get a connection time out from:
```
openssl s_client -connect valadoc.org:443
```
I'm on an IPv4 ISP, so it doesn't help me, but valadoc.org doesn't provide an IPv6 address for it's DNS entry:
```
nslookup -type=AAAA valadoc.org
```

**Comment by lewisgoddard** [comment]
Sorry about this, a server had crashed and it took me a couple of days to get to it. Should be fixed as of 21:00 GMT on the 7th.
