### ISSUE TITLE
Add "/" keyboard shortcut to focus on search bar

### ISSUE THREAD

**Issue by colinkiama** [vala-lang/valadoc-org#408]
It would be a convenient for people who perform multiple searches when visiting valadoc.org.

You wouldn't have to move your cursor and click on the search bar every time anymore.

**Comment by lewisgoddard** [comment]
This is currently already bound to `ctrl` in [`data/scripts/valadoc.js` Line 234](https://github.com/vala-lang/valadoc-org/blob/main/data/scripts/valadoc.js#L234)

If we want to add it to `/` too then the code for the case statement is 191.
