### ISSUE TITLE
Add a Dockerfile

### ISSUE THREAD

**Issue by benwaffle** [vala-lang/valadoc-org#50]
with search capabilities

**Comment by arteymix** [comment]
Actually, I would rather see a Vagrantfile there because it seems like this app is deployed along with https://github.com/elementary/website. I don't think we should use Docker unless we plan to deploy using it.

**Comment by btkostner** [comment]
The site is actually deployed on bare metal without any docker or vagrant file. It's all done with ansible.

The reason I would add a Dockerfile for travis ci testing. It's also nice for quick development, and so people now how to setup a proper environment.

**Comment by arteymix** [comment]
There's a `Vagrantfile` in #40 which is supposed to reproduce the deployment environment. It has Sphinx working so far and of course the current reimplementation in Vala.

**Comment by btkostner** [comment]
Alright. I'm going to update this and say using a `Dockerfile` would be really nice. I'm planning on using the new kubernetes Digital Ocean service for the elementary infrastructure. Creating a `Dockerfile` for valadoc would allow us to have travis run a cron task that could auto deploy valadoc.

**Comment by arteymix** [comment]
I fully agree.

If we use docker-compose, we can setup Sphinx as well and minimize the work needed to get a running instance locally.

With the Valum backend, you could even add a robust HTTP server (i.e. nginx) for facing the Web and deliver resources, and communicate internally using SCGI.
